
name: Update F1 standings

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Update standings
        run: python scripts/f1_standings.py

      - name: Commit & push README
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md scripts/data/f1_cache.json || true
          git commit -m "chore: update F1 standings (auto)" || echo "No changes"
          git push
